name: Blog Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
    
jobs:
  run_swift_script:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Swift Script
        run: |
          swift main.swift
      - name: Push changes
        run: |
          git config --global user.name "Buildbot"
          git config --global user.email "buildbot@users.noreply.github.com"
          git add .
          git commit -m "[BOT] Update Post"
          git push -f
